export const HomeActionTypes = {
SET_TOTAL_USERS:'SET_TOTAL_USERS',
SET_TOTAL_BALANCE:'SET_TOTAL_BALANCE',
SET_ACTIVE_USERS:'SET_ACTIVE_USERS', 
SET_DEPOSITS_TRANSACTION:'SET_DEPOSITS_TRANSACTION'   
}



