const WalletTypes = {
    ADD_WALLET_START: '[WALLET] ADD_WALLET_START START',
    ADD_WALLET_SUCCESS: '[WALLET] ADD_WALLET_SUCCESS',
    UPDATE_WALLET_START: '[WALLET] UPDATE_WALLET_START START',
    UPDATE_WALLET_SUCCESS: '[WALLET] UPDATE_WALLET_SUCCESS',
    WITHDRAW_WALLET_START: '[WALLET] WITHDRAW_WALLET_START START',
    WITHDRAW_WALLET_SUCCESS: '[WALLET] WITHDRAW_WALLET_SUCCESS',
    GET_ALL_WALLETS: '[WALLET] GET ALL WALLETS',
    GET_ALL_WALLETS_SUCCESS: '[WALLET] GET ALL WALLETS_SUCCESS',
    GET_TRANSACTIONS_BY_WALLET: '[WALLET] GET_TRANSACTIONS_BY_WALLET',
    GET_TRANSACTIONS_BY_WALLET_SUCCESS: '[WALLET] GET_TRANSACTIONS_BY_WALLET_SUCCESS',
    GET_ALL_MESSAGES: '[WALLET] GET ALL MESSAGES',
    GET_ALL_MESSAGES_SUCCESS: '[WALLET] GET ALL MESSAGES_SUCCESS',
    DOWNLOAD_ATTACHMENT_START: '[WALLET] DOWNLOAD_ATTACHMENT_START START',
    DOWNLOAD_ATTACHMENT_SUCCESS: '[WALLET] DOWNLOAD ATTACHMENT SUCCESS',
    SEND_MSG_START: '[WALLET] SEND MSG START',
    SEND_MSG_SUCCESS: '[WALLET] SEND MSG SUCCESS',
    WALLET_RESET: '[WALLET] WALLET_RESET',
    WALLET_RESET_SUCCESS: '[WALLET] WALLET_RESET_SUCCESS',
    ERROR: '[WALLET] ERROR',
    OPTIMIZE_WALLET_START: '[WALLET] OPTIMIZE_WALLET_START START',
    OPTIMIZE_WALLET_SUCCESS: '[WALLET] OPTIMIZE_WALLET_SUCCESS'
};

export default WalletTypes;